version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
    groups:
      radix:
        patterns:
          - '@radix-ui/*'
      codemirror:
        patterns:
          - '@codemirror/*'
          - '@uiw/*'
      xterm:
        patterns:
          - '@xterm/*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    labels:
      - 'dependencies'
