/**
 * Olympus Vault Periodic Notes — Type Definitions
 * ===================================================
 *
 * Types for daily / weekly per-god session summaries. Generated by the
 * heartbeat (the Callimachus agent calls `generateDaily(god, date)` at the
 * end of each session).
 * License: AGPL-3.0-or-later (original OLYMPUS code).
 */

/** Result of generating a daily or weekly summary note. */
export interface PeriodicNoteResult {
  /** Output path (POSIX-style, relative to vault root). */
  path: string;
  /** Rendered Markdown content. */
  content: string;
  /** Size in bytes. */
  size: number;
}

/** A single activity feed event parsed from `06_Activity_Feed/live.jsonl`. */
export interface ActivityEvent {
  /** ISO date string (YYYY-MM-DD). */
  date: string;
  /** Time-of-day string (HH:MM) if present in the heading. */
  time?: string;
  /** God name (lowercase). */
  god: string;
  /** Task description (from `- Task:` line). */
  task?: string;
  /** Input tokens (from `- Tokens in:` line). */
  tokensIn?: number;
  /** Output tokens (from `- Tokens out:` line). */
  tokensOut?: number;
  /** Duration in seconds (from `- Duration:` line). */
  durationSeconds?: number;
  /** Outcome (from `- Outcome:` line). */
  outcome?: string;
  /** Sub-agent dispatched (from `- Sub-agent:` line). */
  subAgent?: string;
  /** Sub-agent score (parsed from sub-agent line). */
  subAgentScore?: number;
}

/** A single working-memory session entry parsed from a god's working-memory.md. */
export interface SessionEntry {
  /** ISO date string (YYYY-MM-DD). */
  date: string;
  /** Heading text (e.g. "JWT auth implementation"). */
  title: string;
  /** Task (from `- Task:` line). */
  task?: string;
  /** Sub-agent dispatched (from `- Sub-agent:` line). */
  subAgent?: string;
  /** Sub-agent score (parsed from sub-agent line). */
  subAgentScore?: number;
  /** Outcome (from `- Outcome:` line). */
  outcome?: string;
  /** Confidence (parsed from outcome line). */
  confidence?: number;
  /** Total tokens (from `- Tokens:` line). */
  tokens?: number;
  /** Skills loaded (from `- Skills loaded:` line). */
  skillsLoaded?: string[];
  /** Files touched (from `- Files:` line). */
  files?: string[];
  /** Instinct formed (from `- Instinct formed:` line). */
  instinctFormed?: string;
  /** Instinct confidence (parsed from instinct line). */
  instinctConfidence?: number;
  /** Instinct sample count (parsed from instinct line). */
  instinctSamples?: number;
}

/** Aggregated daily summary for a single god + date. */
export interface DailySummary {
  god: string;
  date: string; // YYYY-MM-DD
  /** Activity feed events for this god on this date. */
  events: ActivityEvent[];
  /** Working-memory session entries for this god on this date. */
  sessions: SessionEntry[];
  /** Tasks completed (counted from working-memory `- [x]` on this date). */
  tasksCompleted: number;
  /** Total input tokens across all events. */
  totalTokensIn: number;
  /** Total output tokens across all events. */
  totalTokensOut: number;
  /** Total duration in seconds. */
  totalDurationSeconds: number;
  /** Distinct sub-agents dispatched. */
  subAgentsDispatched: string[];
  /** Instincts formed (new) — names. */
  instinctsFormed: string[];
  /** Instincts reinforced (used in sessions) — names. */
  instinctsReinforced: string[];
  /** Escalations (sessions with outcome containing "escalat"). */
  escalations: number;
}

/** Aggregated weekly summary for a single god + week. */
export interface WeeklySummary {
  god: string;
  /** ISO date string for the Monday of the week (YYYY-MM-DD). */
  weekStart: string;
  /** ISO date string for the Sunday of the week (YYYY-MM-DD). */
  weekEnd: string;
  /** Per-day totals (Mon..Sun; entries for days with no activity are zeroed). */
  daily: DailySummary[];
  /** Total tasks completed across the week. */
  totalTasksCompleted: number;
  /** Total tokens in. */
  totalTokensIn: number;
  /** Total tokens out. */
  totalTokensOut: number;
  /** Total duration in seconds. */
  totalDurationSeconds: number;
  /** Distinct sub-agents dispatched across the week. */
  subAgentsDispatched: string[];
  /** Instincts formed across the week. */
  instinctsFormed: string[];
  /** Escalations across the week. */
  escalations: number;
  /** Trend vs previous week (positive = up). */
  trend: {
    tasksCompletedDelta: number;
    tokensDelta: number;
    escalationsDelta: number;
  };
}

/** Configuration for the periodic generator. */
export interface SummaryConfig {
  /** Path to the session-summary template (default: `08_Templates/session-summary.md`). */
  templatePath?: string;
  /** Override the output directory (default: `01_Gods/<God>/activity/`). */
  outputDir?: string;
}
